In [56]:
import caption_contest_data as ccd
import numpy as np
from thompson import ThompsonSampling

In [71]:
contests = list(ccd.summary_ids())
cont = []
contests = [i for i in contests if type(i) == int]
print(len(contests))

168

In [75]:
for idx,i in enumerate(contests):
    df = ccd.summary(i)
    if (df.query('rank == 10')['count'] < 1000).squeeze():
        contests.remove(i)

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

,target_id,rank,funny,somewhat_funny,unfunny,count,score,precision,contest,caption
0,2528,1,4321,5753,2664,12738,2.130083,0.006459,691,"Should I check, “exceeded expectations?”"
1,2611,2,3548,4645,2978,11171,2.051025,0.007216,691,Let’s just give him the damn cheese.
2,3080,3,3548,4383,3060,10991,2.044400,0.007384,691,"Hmmmmm, we didn’t count on his thinking above ..."
3,754,4,3432,4070,3034,10536,2.037775,0.007624,691,'What's more impressive is he's already filed ...
4,294,5,3557,4130,3278,10965,2.025445,0.007536,691,"Oddly, this one got the placebo."
5,3568,6,3191,3786,3241,10218,1.995107,0.007849,691,"He doesn't just find the cheese, he offers sam..."
6,3619,7,2582,2850,2805,8237,1.972927,0.008906,691,He also submitted a resume for your job.
7,3251,8,2848,3687,3124,9659,1.971426,0.007996,691,It appears that his 'fight or flight' response...
8,1224,9,2143,3213,2369,7725,1.970744,0.008690,691,Maybe we should start with a smaller dose.
9,289,10,2531,3246,2903,8680,1.957143,0.008481,691,I hurt his feelings last week when I told him ...
10,2953,11,2434,3336,2857,8627,1.950968,0.008416,691,We're going to need another grant
11,1627,12,2212,2417,2673,7302,1.936867,0.009544,691,Rat maze navigation trial 14: Animal failed to...
12,2761,13,2086,3109,2697,7892,1.922580,0.008720,691,Do you suppose they’ve been toying with us all...
13,2394,14,2164,2792,2943,7899,1.901380,0.008979,691,I'll bet HE could build a better mousetrap.
14,3013,15,1355,1788,1866,5009,1.897984,0.011239,691,"He calls it a ""Rat Pack"""
15,3413,16,1879,2155,2619,6653,1.888772,0.009989,691,She’s smart. Looks like we’ll need the glass c...
16,2152,17,1704,2530,2552,6786,1.875037,0.009494,691,"Yes, that's cool. But it's not statistically ..."
17,2620,18,1931,2134,2789,6854,1.874818,0.009910,691,"He flies and poops everywhere. Essentially, we..."
18,1424,19,1745,2894,2773,7412,1.861306,0.008925,691,He also left us a tiny note with suggested rev...